from enum import Enum


class ErrorCode(str, Enum):
    NO_LEAF = "NO_LEAF"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    GPT_TIMEOUT = "GPT_TIMEOUT"
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    UPGRADE_REQUIRED = "UPGRADE_REQUIRED"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    FORBIDDEN = "FORBIDDEN"
