name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///./test.db
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff
      - name: Run Ruff
        run: ruff app tests
      - name: Run Tests
        run: pytest -q

  bot-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install bot dependencies
        run: npm ci --prefix bot
      - name: Run bot tests
        run: npm test --prefix bot
